# GitHub Actions Workflow: Vampi build pipeline with security test
name: Vampi build pipeline with security test

on:
  push:                         # Trigger on any push
  repository_dispatch:         # Allow external systems to trigger via repository_dispatch
  workflow_dispatch:           # Allow manual triggering from the GitHub UI

jobs:
  scan:
    runs-on: ubuntu-latest     # Use the latest Ubuntu runner

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Check out the repository contents

      - name: Run VAmPI 
        run: docker compose up -d  # Start VAmPI API using Docker Compose in detached mode

      - name: Test VAmPI
        run: sleep 5 && curl http://localhost:5002/ --retry 10 --retry-delay 1 
        # Wait for service to start, then ping the API to ensure it's up (retry up to 10 times)

      - name: Createdb
        run: curl http://localhost:5002/createdb 
        # Initialize VAmPI with test data

      - name: Run Active Scan
        uses: nonamesec/active-scan-action@v1
        with:
          ENV_ID: ${{ secrets.ENV_ID }}

          ACTIVE_REGISTRY_URL: us-central1-docker.pkg.dev/noname-artifacts/nns-docker
          ACTIVE_REGISTRY_USER: _json_key_base64
          ACTIVE_REGISTRY_PASSWORD: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

          ACTIVE_API_URL: https://adam-lab.nonamesec.com/active
          ACTIVE_API_TOKEN: ${{ secrets.ACTIVE_API_TOKEN }}
          ACTIVE_BACKEND_URI: https://adam-lab.nonamesec.com/active/backend

          TEST_GROUP_ID: ${{ secrets.TEST_GROUP_ID }}

          BRANCH_NAME: ${{ github.ref_name }}

          VERBOSE: "true"
          ANALYZE: "false"

      - name: Stop VAmPI
        if: always()
        run: docker compose down

  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        run: |
          echo "VAmPI security scan passed."
          echo "Deploying to production..."
          # Add your deployment commands here
