# GitHub Actions Workflow: Vampi build pipeline with security test
name: Vampi build pipeline with security test

on:
  push:                         # Trigger on any push
  repository_dispatch:         # Allow external systems to trigger via repository_dispatch
  workflow_dispatch:           # Allow manual triggering from the GitHub UI

jobs:
  scan:
    runs-on: ubuntu-latest     # Use the latest Ubuntu runner

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Check out the repository contents

      - name: Run VAmPI 
        run: docker compose up -d  # Start VAmPI API using Docker Compose in detached mode

      - name: Test VAmPI
        run: sleep 5 && curl http://localhost:5002/ --retry 10 --retry-delay 1 
        # Wait for service to start, then ping the API to ensure it's up (retry up to 10 times)

      - name: Createdb
        run: curl http://localhost:5002/createdb 
        # Initialize VAmPI with test data

      - name: Active Scan
      on:
        push:
          branches: [ main ]
        pull_request:
      
      jobs:
        active-scan:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Run Active Scan
              uses: nonamesec/active-scan-action@v1
              with:
                ENV_ID: "0837679f-9f9f-48a2-90b5-739fc891d162"
                ACTIVE_REGISTRY_URL: "us-central1-docker.pkg.dev/noname-artifacts/nns-docker"
                ACTIVE_REGISTRY_USER: "_json_key_base64"
                ACTIVE_REGISTRY_PASSWORD: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9uYW1lLWFydGlmYWN0cyIsCiAgInByaXZhdGVfa2V5X2lkIjogImY4NDE5ZjVhMmY3ZDQ5N2JjMmE2YjZmMzYyNGU0ZWZkNmM5NDE1MWYiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFNVaGVyNWJ1cXlDZEpcbklwaGVxbUcvUkVSWVZhd3ZUM0twRmY3cDZuQjdsdWxTWGpDLyswZjJ2TTFlN3hvelpPOFJFYUxSMGdxNTNxd3Vcbi9ZNEE1MkVzOXJDczd6UzVESEhFZXdSY2ZPWFU3M3VkK1JEMitFSEYwNW1qdlFJenVVWXZnL2x3aU0zdkh5bThcbjZtVXdlY1psbTlSbElQcGk0cEU3NWFJUFdNN3RDSmtWSndENk83SWU4VmRUOFhXdTVrT2g5ZTVjdEdkNFM4N3ZcbmtrWEV1dnZ6aTU3cHB6YWVwMEREc3ZUSFF6OEg4WHNFWDJuMXlyL0dxaFRoL3N0WjN2QXVFMk9PWTY0RXVuMXpcbm51blk2bEM3cFcrMGg2ZE1QM0lUVlpWS2JIUXA1YTF4QVN6emNvKzYybU81SWgwbFJlT3VNWjZhd25vSi85b3Jcbk84Z0NFT1FYQWdNQkFBRUNnZ0VBRXIzekJrUHp0Y2NFZ0djRnRzWGhoMm5xcHp0UXp0RkhIbHdGSUpsZUpCYmtcbmlVQTI1N1paYjZkQ2VLU01MRVI2b0I5M0d3Vk9WNVlWNjFHck1sZWZTNGowbElZblFVNmpmRk8wREJjUmx0dklcbjFwUVVwS0pBT1dwNHNmM3k4TWs2SnpXZEFleTZMZ1l0bUVrRUpnRnNDSzlhdlgyQUlvaTM2K05uQVZxQWhVYUtcbkFkZHdRMENjazVMa0dWa0QrQWlJd1FUcGV0aGtMZzFoQnhPQ2hMbkdFRXl5VmxWZXd2R0tBK3NsamJGbmZ6QTlcbnBaQy93UGFZa0RBNldBK0FyVDhtTXVLSldtZldEMXpuZmQvNGxRc2JEMURUeEtrakJuYjkyZzkySjRKRlc5UE9cblVBdVpSTlhxRnVVU2phZWo1QXR3OFkxaElGdVIrZUZUMmlKdDYzSzV0UUtCZ1FEc1FVMUk4SzZRMllRQUwrUzRcbmUzb0FZU0VhR1BIVy9iUEYyYmpKWE9mdFQxS3l5WEJqd2RwakVNdHVjUUlpWXNUUW1iVC9JRDB1eHlZYWNNbElcblBUWlI2cllBUUdMbHRaeDRYeEJOWTgyYmlDdWpQMDBQdmJ5NTZPNU10cHFxQUEvMHMrWWNNSGp1UldxQzFZSHFcbkVnMzNHbGsxbEtxL0hIOWxtYkZrUGxUZTFRS0JnUURqNWV2c1gwV0FwZEpIdHJDZGI1ekhtZjBVRUZhdWFFeU1cbllJcml5Z0t3U2NINGNBOGRLRm1BMHNtRElwK0QzaXo1c2pWeGNhYXlIYlI2NnhnZWhydkg1RUUyckxEenNDVzFcbjRXQ0s1OFdDNkl5bCt1OExFZnZhR0k3RThVOHo0bWx3WWZOYjlwVW4zRVE2NEdaYVg2cEJOdE9tbFhmSjFwRTFcbkpsKzVEUG5sT3dLQmdENG0rOGI1a21NRzVpUUtkWGhXKzRTSUNPWk5zNm1rZXB2TktFREpFVGFzREl4K1UvUGFcbmRySmpJN0Y5UjF0MmNtS1NYVHhVNWVPZGZwZXNIamZENnJ0b0xOTXFIUnBqU2JPZEJyUGxVcHpkR09YTWJHQjhcbndONkR1ZFV5b01PaVdwQThsNGZJOUxkeVNZLzd6VDZmMjA2cmZ0YUtzdFN1RVpIUCtndnVIZk8xQW9HQkFMYTdcbjFDa0sxMHJwS3l2dmM3dzVFMmdFdENXVFdEMnVTYnJCYW51Z2FQbDdtcm1lK0s5emZCak1hMkhuc0NublN2N0lcbkF3dzhpZUlGNllJcDRZUVFtcDhVQ2FwU1creDUwREwvVFE3eitxNFYwemovZFE3V1U3QXp3cjV0a3dsU1FTTW9cbmx4NmxJRUgrM3dLcWpjZG5MN2ZzdzFhdVFJZXBzWE1CbXYxaFJ6cWpBb0dCQUk4a3pLdjBXUldNN1IyclRFSDlcbitkc1NVUFQ2eGVsSkFNOVlUVVEvWURyc0QyOUQ1Z0pBSnVsTkQyVUVWUDd3TFlyRG85Y0prd0tSTlF2K0RFVXdcbnRvbW5NSkcwUURSYlhZazZDN3ZEdGdXY1ExTkpLNzc0dmR6M2tETnJhblF3bkEvaHBqN0R2bUFQNTNWZURTNmxcbkdqcTNuVlRJZ0V4OHdjNnRPR3g1Q2QwS1xuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImFkYW0tbGFiQG5vbmFtZS1hcnRpZmFjdHMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA3MzcyODU5MDM4NzU3NDA5MjMxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9hZGFtLWxhYiU0MG5vbmFtZS1hcnRpZmFjdHMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
                ACTIVE_API_URL: "https://adam-lab.nonamesec.com/active"
                ACTIVE_API_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlLZXkiOiJhZmU1OTU3ZS02YzliLTRmOTAtYTc5Yy0zYWQ1ZTlhZmFjODciLCJpZCI6IjYxYjRmN2FmLTkyZGUtNDNkMC05NmE2LWUwNTYyNTRmMzYzMyIsImlhdCI6MTc4MzAyMjk1NywiZXhwIjoxNzk4NTc0OTU3LCJhdWQiOlsibm9uYW1lLW1hbmFnZW1lbnQtYXBpIl0sImlzcyI6Im5vYXV0aCJ9.EvBpW0sZ1BahRJqLMh6VIJaroTG5k4_up5QZUpihLaGzj6OWMMgLBxVt7x2EZOQBIy6TIQvOSDqhrLNWIjxds_fY02QlwQSObLMNZOxauwZLUz4C_wabce32ZLKz9UKRDaLXyMo5vQUN7zL3PognGFja28ZUXM2lPwD6p-vZbb7U5H1YaOQSBiYePGRVwPln0fmekWDIZc4Rtajx-dri7Y9TaXKc7bKSg_Aw5xi4Bwq9GvStBCVbPinpTfvD2aFV71sGpurecjQqG_elPa9p2VYDIyTJkh5UEuL7HKkQrlL8oiMJ_nBcQHACK0ig1mODVoSw2Ro63jO92_ZsLF_JoQ"
                ACTIVE_BACKEND_URI: "https://adam-lab.nonamesec.com/active/backend"
                TEST_GROUP_ID: "892b51de-67cf-4328-beea-3ade61bcdeb2"
                BRANCH_NAME: "${{ github.ref_name }}"
                VERBOSE: "true"
                ANALYZE: "false"



  deploy:
    needs: scan                      # Only run if scan job passes
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo Vampi security scan passed, deploying to production
        # Placeholder for deployment; just an echo statement for now
